name: Release

on:
  push:
    tags:
      - 'v*'

env:
  name: hephaistos

jobs:
  release:
    name: Build artifacts and upload release, then rotate changelog
    runs-on: windows-latest
    steps:
      - name: Retrieve tag name
        id: tag
        shell: bash
        run: echo ::set-output name=name::${GITHUB_REF#refs/tags/}

      - name: Checkout files
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Set up Python
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.9

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.3

      - name: Build Windows artifacts with PyInstaller
        run: pyinstaller --onefile ${{ env.name }}.py

      - name: Build release-only changelog
        id: changelog
        shell: bash
        env:
          prog: |
            from pathlib import Path
            import re
            regex = re.compile(r'## \[Unreleased\]\s+(?P<notes>.*?)\s+## ', re.DOTALL)
            changelog = Path('CHANGELOG.md').read_text()
            found = regex.search(changelog)
            if found:
              print(found.group('notes'))
        run: |
          RELEASE_NOTES=$(python -c "${{ env.prog }}")
          echo ::set-output name=release-notes::${RELEASE_NOTES}

      - name: Create release
        uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
        with:
          body: ${{ steps.changelog.outputs.release-notes }}
          files: |
            dist/${{ env.name }}.exe
            ${{ env.name }}.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rotate unreleased section in changelog
        uses: thomaseizinger/keep-a-changelog-new-release@9f6c16b8af7dd10f8aa0ad740fd648b2cfe22171
        with:
          version: ${{ steps.tag.outputs.name }}

      - name: Push updated changelog to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit --message "Release ${{ steps.tag.outputs.name }}"
          git push origin HEAD:main
