name: Release

on:
  push:
    tags:
      - "v*"

env:
  name: hephaistos
  lua_mod: lua

jobs:
  release:
    name: Build artifacts and upload release, then rotate changelog
    runs-on: windows-latest
    steps:
      - name: Retrieve tag name
        id: tag
        shell: bash
        run: echo ::set-output name=name::${GITHUB_REF#refs/tags/}

      - name: Checkout files
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          submodules: true

      - name: Consolidate Python artifacts in a zip
        id: python-artifacts
        run: |
          $zipName = "${{ env.name }}-python.zip"
          Compress-Archive ${{ env.name }},sjson $zipName
          echo "::set-output name=zip-name::$zipName"

      - name: Set up Python
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.9

      - name: Retrieve pip dependencies from cache
        id: cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: |
            ${{ env.pythonLocation }}\lib\site-packages
            ~\AppData\Local\pip\Cache
          key: pip-cache

      - name: Install pip dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==4.3

      - name: Build Windows binaries with PyInstaller
        run: python -m PyInstaller --onefile ${{ env.name }}/__main__.py --name ${{ env.name }}

      - name: Consolidate Windows artifacts in a zip
        id: windows-artifacts
        run: |
          $zipName = "${{ env.name }}-windows-exe.zip"

          # Moving and copying data around so that we zip only the .exe and
          # lua_mod directory, not everything else in the hephaistos directory
          Move-Item ${{ env.name }} tmp
          Copy-Item -Recurse tmp/${{ env.lua_mod }} ${{ env.name }}/${{ env.lua_mod }}
          Compress-Archive  dist/${{ env.name }}.exe,${{ env.name }} $zipName
          Remove-Item -Recurse ${{ env.name }}
          Move-Item tmp ${{ env.name }}

          echo "::set-output name=zip-name::$zipName"

      - name: Build release-only changelog
        id: changelog
        shell: bash
        env:
          prog: |
            from pathlib import Path
            import re
            regex = re.compile(r'## \[Unreleased\]\s+(?P<notes>.*?)\s+## ', re.DOTALL)
            changelog = Path('CHANGELOG.md').read_text()
            found = regex.search(changelog)
            if found:
              print(found.group('notes'))
        run: |
          RELEASE_NOTES=$(python -c "${{ env.prog }}")
          echo ::set-output name=release-notes::${RELEASE_NOTES}

      - name: Create release
        uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
        with:
          body: ${{ steps.changelog.outputs.release-notes }}
          files: |
            ${{ steps.windows-artifacts.outputs.zip-name }}
            ${{ steps.python-artifacts.outputs.zip-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rotate unreleased section in changelog
        uses: thomaseizinger/keep-a-changelog-new-release@9f6c16b8af7dd10f8aa0ad740fd648b2cfe22171
        with:
          version: ${{ steps.tag.outputs.name }}

      - name: Push updated changelog to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit --message "Release ${{ steps.tag.outputs.name }}"
          git push origin HEAD:main
